### PR TITLE
PCG_15_68_User-Story-DADU-Page

### LINKED ISSUE #68: USER STORY: DADU Page
As a developer, I want to add a placeholder page for pre-approvded DADU designs. This page subject to change when we received more information from client.

Link to Seattle Pre-approved DADU designs: https://aduniverse-seattlecitygis.hub.arcgis.com/pages/gallery

Link to Figma design: https://www.figma.com/design/ESh8evwOMnwZ5e35RVwSWr/PCG?node-id=0-1&t=aW7rfAGRRBWlBMDV-1

DADU placeholder

### PR DESCRIPTION
**Pull request by JoyZhang2023**
Resolves #68 

This pull request is to add a placeholder page for DADU/ADU with some Seattle pre-approved DADU designs. This page will be update when we receive more instruction from Ryan.

image

### CODE REVIEW

**Comment by Diego-Cano** [comment]
This pull request sets up a placeholder page for the pre-approved DADU designs, following the client’s request to make the permitting process easier and accessible. The design is simple but functional, with a clear layout that highlights DADU options and links to Seattle’s official resources. I tested the functionality, and everything loads as expected without any issues. It’s a solid start, though I think adding more descriptive alt text for the images would make the page more accessible and polished.

I like how this pull request lays the groundwork for future updates while keeping the design clean and user-friendly. It’s clear that thought was put into making it easy to expand on later. Nice job putting this together! I found a useful link about DADUs, here’s a great resource from the City of Seattle: [ADUniverse page](https://aduniverse-seattlecitygis.hub.arcgis.com/pages/gallery).

Screenshot 2024-11-24 at 10 36 48 AM

**Review by Diego-Cano — APPROVED** [review]
Looks good!

**Review by gitbiruk2010 — APPROVED** [review]
The new dadu page and the nav bar adjustment looks good on my end.

**Review by larsswenson — APPROVED** [review]
Great work, thank you for taking this on!

**Comment by ParysUnangst** [comment]
Everything looks great! Well done!

**Pull request merged**
