### PR TITLE
pelletier-group-nextjs-12-90-Builder-Page

### PR DESCRIPTION
**Pull request by Diego-Cano**
This pull request adds a new Blueprint page to the application, implementing a basic layout with a responsive design. It includes a header and footer. This update will serve as the foundation for further development of the Blueprint Builder feature.

Screenshot 2024-10-12 at 10 59 07 AM

### CODE REVIEW

**Review by larsswenson — APPROVED** [review]
Great start to implementing the Blueprint Builder page! My suggestions are subtle but I think worth addressing, perhaps in a future issue / PR. I think some of the wording could be edited to be even more explicit as per UI/UX best practices. Changing "What would you want to build?" to simply, "What do you want to build?" is less vague and passive and effectively utilizes action verbs. Also, changing "Any additional info?" to "Any additional info you'd like us to know?" personalizes it a bit. Although seemingly minor, these linguistic differences affect user behavior. Great work!

**Review by BradleyCharles — APPROVED** [review]
Looks like a good start that can be built upon later. Good job!

Screenshot 2024-10-13 135007

**Review by ken-ni — APPROVED** [review]
I tested the blueprint page and was able to successfully submit one, great job! One thing I noticed (not sure if it's only on my end) is that one of the components on the landing page breaks when loading it on this branch.

Landing page main branch:
Screenshot from 2024-10-15 15-34-41

Landing page this branch:
Screenshot from 2024-10-15 15-36-52

Error:
Screenshot from 2024-10-15 15-37-13

EDIT: The hydration error is actually on other branches too, and is separate from the landing page component not rendering (this was fixed since my comment).

**Review by JoyZhang2023 — APPROVED** [review]
Blueprint builder page works great! Good job! I got same error message on landing page. But it went away when I switch back to home page from builder page. 
image

**Pull request merged**
