### PR TITLE
pcg_12_43_Home_Page

### LINKED ISSUE #43: USER STORY: Home Page
As a developer, I want to copy over missing page section from [PelletierConstructionGroup.github.io](https://github.com/PelletierConstructionGroup/PelletierConstructionGroup.github.io). 

Issues: 

- [ ] Project showcase
- [ ] Get Estimate Section (redirect to Contact page)

Pelletier-Construction-Group-10-01-2024_06_27_PM

### PR DESCRIPTION
**Pull request by JoyZhang2023**
Resolves #43 

This pull request is to resolve issue #43 by copying Get Estimate block over using Typescript. The home page should have below section added.
Screenshot 2024-10-06 202649

### CODE REVIEW

**Review by el-riber — COMMENTED** [review]
Looks like you fixed the problem..

**Review by larsswenson — APPROVED** [review]
Looks great and as expected! Buttons function properly, as well. Nice work!

**Comment by Diego-Cano** [comment]
Great work on adding the 'Get Estimate' section! The new card component looks clean and integrates well with the overall design. I tested the button functionality, and it redirects properly to the Contact page. One suggestion I have is to consider adding a bit more padding around the button for a better mobile experience. Other than that, everything looks good. Nice job!
Also, I found a helpful link on [Material-UI](https://medium.com/@egwuchinedu69/how-to-build-a-responsive-web-app-with-material-ui-fd6b9f0cdce6) that explains the topic.

**Review by Diego-Cano — APPROVED** [review]
Great work on adding the 'Get Estimate' section! The new card component looks clean and integrates well with the overall design. I tested the button functionality, and it redirects properly to the Contact page. One suggestion I have is to consider adding a bit more padding around the button for a better mobile experience. Other than that, everything looks good. Nice job!

**Pull request merged**
