### PR TITLE
PCG_13_58_user-story-projects-page

### LINKED ISSUE #58: USER STORY: Projects Page
As a developer, I want to add "Our Builds" section to projects page.
image

### PR DESCRIPTION
**Pull request by JoyZhang2023**
Resolves #58 
This pr adds "Our Builds" to projects page.
image

### CODE REVIEW

**Comment by Diego-Cano** [comment]
This pull request addresses user story #58 by adding an "Our Builds" section to the projects file. It effectively uses Material-UI components, such as Box, Typography, and ImageList, to create a responsive image grid that displays different builds. The itemData array is structured with images and titles, providing a consistent layout that aligns well with the design expectations. One suggestion for improvement would be to add descriptive alt text for the images to enhance accessibility, especially for users relying on screen readers. This setup not only meets the functional requirements but also demonstrates best practices for implementing modern design with Material-UI. Reviewing this PR has reinforced the importance of accessibility considerations and efficient component organization in web development. Here’s a useful link to documentation on [responsive design and accessibility practices.
](https://www.levelaccess.com/blog/what-does-responsive-web-design-have-to-do-with-accessibility/)

Screenshot 2024-11-03 at 9 49 58 AM

**Review by Diego-Cano — APPROVED** [review]
Great Job!

**Comment by larsswenson** [comment]
Please add the relevant label, projects, etc and confirm this is ready for review to convert from draft status (LGTM!), as well as requesting reviewers. Nice work & thanks!

**Review by ogarmela — APPROVED** [review]

**Review by gitbiruk2010 — CHANGES_REQUESTED** [review]
Hi @JoyZhang2023 
The newly added Our Builds page looks great on my end—well done! 👏
However, I noticed that the hydration error is still present when testing this branch. I have submitted a separate pull request that includes a fix for this hydration error. Once my PR is reviewed and merged, I recommend pulling the latest changes to ensure that the hydration issue is resolved across the entire project.
 
PR Review Snap

**Comment by JoyZhang2023** [comment]
@gitbiruk2010  Sound good! Will update this pull request once your pr was merged. Thank you!

**Review by ogarmela — APPROVED** [review]

**Review by larsswenson — APPROVED** [review]
Looks great, nice work!

**Review by ParysUnangst — APPROVED** [review]
Images look great Joy!

**Comment by JoyZhang2023** [comment]
@gitbiruk2010 I have rebased this branch and the hydration error is gone. Let me know if it looks good now. Thanks!

**Review by larsswenson — APPROVED** [review]
I believe requested changes have been addressed.

**Review by gitbiruk2010 — APPROVED** [review]

**Pull request merged**
