### PR TITLE
pcg_12_46_Testimonial_Page

### LINKED ISSUE #50: Create testimonial page from original
I am creating the testimonial page from the original design.

### PR DESCRIPTION
**Pull request by BradleyCharles**
Resolves #50 

This PR will  add the completed testimonial page. 
I also created the Carousel component for the reviews and made it modular so it can be reused in other pages/projects.

Screenshot 2024-10-12 112053

Screenshot 2024-10-12 111915

Screenshot 2024-10-12 111941

### CODE REVIEW

**Review by larsswenson — APPROVED** [review]
Looks great, Bradley! One thing I noticed is that when the carousel switches between the two reviews automatically, it switches before it can be read completely. Perhaps we could lengthen the time it takes before switching to the next review? It's not a major deal but this should be another issue to address going forward. Also, perhaps we could add some animation so that the carousel "scrolls" between the reviews left to right? Nice work!

**Comment by BradleyCharles** [comment]
> Looks great, Bradley! One thing I noticed is that when the carousel switches between the two reviews automatically, it switches before it can be read completely. Perhaps we could lengthen the time it takes before switching to the next review? It's not a major deal but this should be another issue to address going forward. Also, perhaps we could add some animation so that the carousel "scrolls" between the reviews left to right? Nice work!

I agree that it moves too quickly. It was originally a 2 second wait and I had increased it to 5 but that still feels too fast. I just changed it to 10 seconds and it feels better. I also added props to the carousel component so the speed can be controlled more easily and independently. 

I think we could definitely make it look nicer with some cool animations but I think that would be better for another day.

**Review by JoyZhang2023 — APPROVED** [review]
LGTM! Great work! All section displays correctly and carousel works fine.

**Review by el-riber — APPROVED** [review]
Screenshot 2024-10-13 at 9 37 02 PM

it is working perfect! good work!

**Pull request merged**
